### ISSUE TITLE
Query about the evaluation method codes

### ISSUE THREAD

**Issue by tangqideng** [ML4ITS/TimeVQVAE-AnomalyDetection#1]
Thanks for your nice work. Would you mind upload the evaluation method codes?  Then we can reproduce the results in your paper using the uploaded anomaly scores. Thanks for your help.

**Comment by danelee2601** [comment]
Thanks for your interest. I've been thinking of how to do that, but taking out the evaluation code was a bit tricky as we evaluate through many visualizations and the detection accuracy. 

The calculation of detection accuracy should be straightforward and easy to implement, while the visualizations may not. Our paper got a minor revision recently, and hoping that it'd get accepted soon, and we'll publish the codes asap.

**Comment by danelee2601** [comment]
good news. Our paper has been just accepted at the Pattern Recognition journal. The code will be made available soon.
