### ISSUE TITLE
model implementation

### ISSUE THREAD

**Issue by firatbey** [ML4ITS/TimeVQVAE-AnomalyDetection#2]
Hi, when will you be releasing the model and possibly pre trained models.

**Comment by danelee2601** [comment]
The paper is currently under review in a journal, and we got a minor revision from the reviewers and re-submitted the paper recently. Hopefully, our paper will be accepted soon. We're expecting that we should be able to release the codes soon.

**Comment by danelee2601** [comment]
good news. Our paper has been just accepted at the Pattern Recognition journal. The code will be made available soon.
