### ISSUE TITLE
Issue running steps in README - Please could you confirm package version requirements?

### ISSUE THREAD

**Issue by daniel-mannion** [ML4ITS/TimeVQVAE-AnomalyDetection#4]
Hi, first off, thanks for providing the code to your model! I've followed the steps provided in the README but the training of stage 1 does not run. I get the following error:

![image](https://github.com/user-attachments/assets/09c81d00-3ba4-4b39-93f6-3f94ed51f78c)

This seems it could be an issue with which versions of packages are being used. I started with an empty venv and installed packages using the provided requirements.txt. The pip freeze from the resultant environment is attached below.m Not all package versions have been specified, I'm wondering if the most recent version of these packages are incompatible... **Please could you confirm which versions of packages you are using?** I can then try these and test if that was the issue or not. 

[packages.txt](https://github.com/user-attachments/files/16557089/packages.txt)

**Comment by daniel-mannion** [comment]
Ahh I've just tried reverting numpy from 2.0 to 1.26.4 and it corrected the issue. I'll submit a pull request with a modified requirements file if that helps.

**Comment by danelee2601** [comment]
thanks for the contribution! never thought numpy version would be an issue.

**Comment by daniel-mannion** [comment]
No worries I had a similar problem with a repo recently. It looks like numpy 2.0 has a tendency to break things.
